/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as MyBookingsRouteImport } from './routes/my-bookings'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as StylesRouteImport } from './routes/styles'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardLayoutRouteImport } from './routes/dashboard/_layout'
import { Route as DashboardAccountRouteImport } from './routes/dashboard/account'
import { Route as DashboardAvailabilityRouteImport } from './routes/dashboard/availability'
import { Route as DashboardBookingsRouteImport } from './routes/dashboard/bookings'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardServicesRouteImport } from './routes/dashboard/services'
import { Route as ShopsIndexRouteImport } from './routes/shops.index'
import { Route as ShopsShopIdRouteImport } from './routes/shops.$shopId'
import { Route as AuthCallbackRoleRouteImport } from './routes/auth.callback.$role'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBookingsRoute = MyBookingsRouteImport.update({
  id: '/my-bookings',
  path: '/my-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const StylesRoute = StylesRouteImport.update({
  id: '/styles',
  path: '/styles',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/dashboard/_layout',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAccountRoute = DashboardAccountRouteImport.update({
  id: '/dashboard/account',
  path: '/dashboard/account',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAvailabilityRoute = DashboardAvailabilityRouteImport.update({
  id: '/dashboard/availability',
  path: '/dashboard/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBookingsRoute = DashboardBookingsRouteImport.update({
  id: '/dashboard/bookings',
  path: '/dashboard/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/dashboard/profile',
  path: '/dashboard/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardServicesRoute = DashboardServicesRouteImport.update({
  id: '/dashboard/services',
  path: '/dashboard/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsIndexRoute = ShopsIndexRouteImport.update({
  id: '/shops/',
  path: '/shops/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsShopIdRoute = ShopsShopIdRouteImport.update({
  id: '/shops/$shopId',
  path: '/shops/$shopId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoleRoute = AuthCallbackRoleRouteImport.update({
  id: '/$role',
  path: '/$role',
  getParentRoute: () => AuthCallbackRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/my-bookings': typeof MyBookingsRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/styles': typeof StylesRoute
  '/auth/callback': typeof AuthCallbackRouteWithChildren
  '/dashboard': typeof DashboardLayoutRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/availability': typeof DashboardAvailabilityRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/shops/$shopId': typeof ShopsShopIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/shops/': typeof ShopsIndexRoute
  '/auth/callback/$role': typeof AuthCallbackRoleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/my-bookings': typeof MyBookingsRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/styles': typeof StylesRoute
  '/auth/callback': typeof AuthCallbackRouteWithChildren
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/availability': typeof DashboardAvailabilityRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/shops/$shopId': typeof ShopsShopIdRoute
  '/shops': typeof ShopsIndexRoute
  '/auth/callback/$role': typeof AuthCallbackRoleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/my-bookings': typeof MyBookingsRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/styles': typeof StylesRoute
  '/auth/callback': typeof AuthCallbackRouteWithChildren
  '/dashboard/_layout': typeof DashboardLayoutRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/availability': typeof DashboardAvailabilityRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/shops/$shopId': typeof ShopsShopIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/shops/': typeof ShopsIndexRoute
  '/auth/callback/$role': typeof AuthCallbackRoleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/my-bookings'
    | '/pricing'
    | '/profile'
    | '/styles'
    | '/auth/callback'
    | '/dashboard'
    | '/dashboard/account'
    | '/dashboard/availability'
    | '/dashboard/bookings'
    | '/dashboard/profile'
    | '/dashboard/services'
    | '/shops/$shopId'
    | '/dashboard/'
    | '/shops/'
    | '/auth/callback/$role'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/my-bookings'
    | '/pricing'
    | '/profile'
    | '/styles'
    | '/auth/callback'
    | '/dashboard'
    | '/dashboard/account'
    | '/dashboard/availability'
    | '/dashboard/bookings'
    | '/dashboard/profile'
    | '/dashboard/services'
    | '/shops/$shopId'
    | '/shops'
    | '/auth/callback/$role'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/my-bookings'
    | '/pricing'
    | '/profile'
    | '/styles'
    | '/auth/callback'
    | '/dashboard/_layout'
    | '/dashboard/account'
    | '/dashboard/availability'
    | '/dashboard/bookings'
    | '/dashboard/profile'
    | '/dashboard/services'
    | '/shops/$shopId'
    | '/dashboard/'
    | '/shops/'
    | '/auth/callback/$role'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  MyBookingsRoute: typeof MyBookingsRoute
  PricingRoute: typeof PricingRoute
  ProfileRoute: typeof ProfileRoute
  StylesRoute: typeof StylesRoute
  DashboardLayoutRoute: typeof DashboardLayoutRoute
  DashboardAccountRoute: typeof DashboardAccountRoute
  DashboardAvailabilityRoute: typeof DashboardAvailabilityRoute
  DashboardBookingsRoute: typeof DashboardBookingsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardServicesRoute: typeof DashboardServicesRoute
  ShopsShopIdRoute: typeof ShopsShopIdRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  ShopsIndexRoute: typeof ShopsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-bookings': {
      id: '/my-bookings'
      path: '/my-bookings'
      fullPath: '/my-bookings'
      preLoaderRoute: typeof MyBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/styles': {
      id: '/styles'
      path: '/styles'
      fullPath: '/styles'
      preLoaderRoute: typeof StylesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_layout': {
      id: '/dashboard/_layout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/account': {
      id: '/dashboard/account'
      path: '/dashboard/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/availability': {
      id: '/dashboard/availability'
      path: '/dashboard/availability'
      fullPath: '/dashboard/availability'
      preLoaderRoute: typeof DashboardAvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/bookings': {
      id: '/dashboard/bookings'
      path: '/dashboard/bookings'
      fullPath: '/dashboard/bookings'
      preLoaderRoute: typeof DashboardBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/dashboard/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/services': {
      id: '/dashboard/services'
      path: '/dashboard/services'
      fullPath: '/dashboard/services'
      preLoaderRoute: typeof DashboardServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/': {
      id: '/shops/'
      path: '/shops'
      fullPath: '/shops/'
      preLoaderRoute: typeof ShopsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$shopId': {
      id: '/shops/$shopId'
      path: '/shops/$shopId'
      fullPath: '/shops/$shopId'
      preLoaderRoute: typeof ShopsShopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback/$role': {
      id: '/auth/callback/$role'
      path: '/$role'
      fullPath: '/auth/callback/$role'
      preLoaderRoute: typeof AuthCallbackRoleRouteImport
      parentRoute: typeof AuthCallbackRoute
    }
  }
}

interface AuthCallbackRouteChildren {
  AuthCallbackRoleRoute: typeof AuthCallbackRoleRoute
}

const AuthCallbackRouteChildren: AuthCallbackRouteChildren = {
  AuthCallbackRoleRoute: AuthCallbackRoleRoute,
}

const AuthCallbackRouteWithChildren = AuthCallbackRoute._addFileChildren(
  AuthCallbackRouteChildren,
)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  MyBookingsRoute: MyBookingsRoute,
  PricingRoute: PricingRoute,
  ProfileRoute: ProfileRoute,
  StylesRoute: StylesRoute,
  DashboardLayoutRoute: DashboardLayoutRoute,
  DashboardAccountRoute: DashboardAccountRoute,
  DashboardAvailabilityRoute: DashboardAvailabilityRoute,
  DashboardBookingsRoute: DashboardBookingsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardServicesRoute: DashboardServicesRoute,
  ShopsShopIdRoute: ShopsShopIdRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  ShopsIndexRoute: ShopsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
